#!/bin/bash

if ! command -v kubectl &> /dev/null; then
  echo "kubectl could not be found. Please install kubectl to proceed."
  exit 1
fi

if ! command -v wrk &> /dev/null; then
  echo "wrk could not be found. Please install wrk to proceed."
  exit 1
fi

kubectl scale deployment django-messaging-app --replicas=3

kubectl get pods

wrk -t12 -c400 -d30s <service-url>

kubectl top pods

