apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: django-messaging
    version: blue  # Initially points to the blue version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

